topic: 
  name: "t1_benchmark"
  replicationFactor: 1
  partitions: 1

broker:
  url: "pkc-6ojv2.us-west4.gcp.confluent.cloud:9092"
  username: "NU6OWKGDHI4HPWWU"
  password: "fA/SbrrzjqPJ/KHRdey1Icq+VcP0n30dKGhmZ8xNli9a/Vpctgxx/vwaKl+e25FR"

producer:
  enabled: true
  image: "confluentinc/cp-kafka:7.0.1"
  recordsCount: 1000
  recordSizeBytes: 1024
  throughput: "-1"
  acks: "all"
  count: 1

consumer:
  enabled: false
  image: "confluentinc/cp-kafka:7.0.1"
  messagesCount: 1000
  count: 1

e2e:
  enabled: false
  image: "confluentinc/cp-kafka:7.0.1"
  recordsCount: 1000
  recordSizeBytes: 1024
  acks: "all"
